-- GENERATED by test/lib/build-schema.js from test/schema-columns.txt.
-- Do not edit by hand; edit schema-columns.txt and regenerate.

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin noinherit;
  end if;
end $$;

create table pi_client_access (
  id bigint generated always as identity primary key,
  user_id uuid,
  project_id bigint,
  org_id bigint,
  created_at timestamptz default now(),
  email text
);

create table pi_client_summaries (
  id bigserial primary key,
  project_id bigint,
  content_recent text,
  content_full text,
  period_start date,
  period_end date,
  published_at timestamptz default now(),
  published_by text
);

create table pi_comment_periods (
  id text primary key,
  project_id text,
  title text,
  description text,
  start_date date,
  end_date date,
  status text,
  created_at timestamptz default now(),
  period_type text,
  venue text,
  hearing_date date,
  first_ad_date date,
  second_ad_date date,
  federal_register_date date
);

create table pi_commitments (
  id bigserial primary key,
  project_id bigint,
  stakeholder_id bigint,
  commitment text,
  made_to text,
  made_by text,
  date_made date,
  due_date date,
  category text,
  status text,
  fulfilled_date date,
  fulfilled_notes text,
  notes text,
  created_at timestamptz default now()
);

create table pi_deliverables (
  id bigserial primary key,
  project_id text,
  deliverable_type text,
  scope_type text,
  status text,
  contracted_qty integer,
  delivered_count integer,
  freq text,
  milestone_start text,
  milestone_end text,
  dist_list text,
  notes text,
  created_at timestamptz default now(),
  due_date date,
  title text,
  progress integer
);

create table pi_dismissed_pairs (
  id bigserial primary key,
  id_a bigint,
  id_b bigint
);

create table pi_group_members (
  id bigserial primary key,
  group_id bigint,
  stakeholder_id bigint,
  created_at timestamptz default now()
);

create table pi_groups (
  id bigserial primary key,
  project_id bigint,
  name text,
  color text,
  spatial_label text,
  spatial_value text,
  description text,
  sort_order integer,
  created_at timestamptz default now()
);

create table pi_interactions (
  id bigserial primary key,
  project_id text,
  stakeholder_id text,
  interaction_date date,
  channel text,
  subject text,
  nature text,
  direction text,
  summary text,
  logged_by text,
  follow_up boolean,
  follow_up_due date,
  follow_up_note text,
  follow_up_done boolean,
  meeting_id text,
  created_at timestamptz default now(),
  follow_up_resolved date,
  anon_label text,
  nepa_stage text,
  equity_form_submitted boolean,
  updated_at timestamptz default now(),
  updated_by text,
  follow_up_assigned_to text
);

create table pi_issue_interactions (
  id bigserial primary key,
  issue_id bigint,
  interaction_id text
);

create table pi_issues (
  id bigserial primary key,
  project_id text,
  title text,
  category text,
  description text,
  status text,
  priority text,
  date_raised date,
  date_resolved date,
  assigned_to text,
  resolution_summary text,
  created_by text,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  updated_by text
);

create table pi_meetings (
  id bigserial primary key,
  project_id text,
  title text,
  meeting_date date,
  meeting_type text,
  location text,
  status text,
  attendance_count integer,
  comment_cards integer,
  format text,
  key_concerns text,
  action_items text,
  notes text,
  created_at timestamptz default now(),
  handouts text,
  agenda text,
  additional_attendees text,
  equity_form_submitted boolean,
  attendee_ids jsonb
);

create table pi_parcel_owners (
  id bigint generated always as identity primary key,
  parcel_id text,
  stakeholder_id text,
  ownership_role text,
  created_at timestamptz default now()
);

create table pi_parcels (
  id bigint generated always as identity primary key,
  project_id text,
  parcel_number text,
  situs_address text,
  latitude text,
  longitude text,
  acquisition_type text,
  status text,
  notice_date date,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  updated_by text
);

create table pi_portal_links (
  token uuid primary key,
  project_id bigint,
  label text,
  created_at timestamptz default now()
);

create table pi_project_stakeholders (
  id bigserial primary key,
  project_id text,
  stakeholder_id text,
  stakeholder_role text,
  support text,
  distribution_groups text,
  issue_tags text,
  added_date date,
  notes text,
  created_at timestamptz default now(),
  influence text
);

create table pi_projects (
  id bigint generated always as identity primary key,
  name text,
  pid text,
  client text,
  project_type text,
  county text,
  phase text,
  status text,
  start_date date,
  end_date date,
  precon_date date,
  notes text,
  created_at timestamptz default now(),
  last_exported date,
  nepa_classification text,
  nepa_stage text,
  nepa_checklist jsonb,
  phase_history jsonb,
  nepa_stage_history jsonb
);

create table pi_public_comments (
  id text primary key,
  project_id text,
  period_id text,
  comment_date date,
  comment_type text,
  commenter text,
  affiliation text,
  channel text,
  summary text,
  category text,
  sentiment text,
  response_status text,
  response_text text,
  response_date date,
  linked_stakeholder_id text,
  created_at timestamptz default now(),
  commenter_email text,
  responded_by text,
  notes text
);

create table pi_report_archive (
  id bigserial primary key,
  project_id bigint,
  report_num text,
  report_title text,
  report_subtitle text,
  period_start date,
  period_end date,
  overall_summary text,
  sections jsonb,
  archived_at timestamptz default now(),
  archived_by text,
  client_visible boolean,
  snapshot jsonb
);

create table pi_reports (
  id bigserial primary key,
  project_id bigint,
  report_num text,
  report_title text,
  report_subtitle text,
  period_start date,
  period_end date,
  overall_summary text,
  sections jsonb,
  updated_at timestamptz default now(),
  updated_by text,
  editing_email text,
  editing_session text,
  editing_at timestamptz default now(),
  include_internal boolean,
  dist_groups jsonb
);

create table pi_stakeholders (
  id bigint generated always as identity primary key,
  first_name text,
  last_name text,
  org text,
  title text,
  email text,
  phone text,
  address text,
  parcel_id text,
  stakeholder_type text,
  influence_tier text,
  pref_contact text,
  is_master boolean,
  notes text,
  created_at timestamptz default now(),
  is_archived boolean,
  is_lep boolean,
  is_ej boolean,
  stakeholder_role text,
  lep boolean,
  underserved boolean,
  updated_at timestamptz default now(),
  updated_by text
);

create table pi_tribal_consultations (
  id text primary key,
  project_id text,
  tribe_name text,
  tribe_type text,
  thpo_contact text,
  thpo_email text,
  thpo_phone text,
  consultation_type text,
  phase text,
  section106_phase text,
  notification_date date,
  response_deadline date,
  response_date date,
  response_status text,
  tribal_official text,
  tribal_official_email text,
  tribal_official_phone text,
  agency_official text,
  fhwa_liaison text,
  consultation_trigger text,
  language_access_needed boolean,
  moa_required boolean,
  bia_involvement boolean,
  near_tribal_lands boolean,
  cfr710_review boolean,
  row_type text,
  ura_notice_date date,
  bia_approval_status text,
  utah_pa_ref text,
  certification_status text,
  included_in_annual_report boolean,
  annual_report_year text
);

create unique index pi_portal_links_proj_uniq on pi_portal_links(project_id);

create unique index pi_parcels_proj_number_uniq on pi_parcels (project_id, lower(trim(parcel_number)));

create unique index pi_parcel_owners_uniq on pi_parcel_owners (parcel_id, stakeholder_id);

alter table pi_client_access add constraint pi_client_access_email_project_uniq unique (email, project_id);
