#!/usr/bin/env node
// Regenerates test/schema.sql from test/schema-columns.txt.
//
// schema-columns.txt is a verbatim dump of the live database, INCLUDING COLUMN
// TYPES — that is the reason the drift test means anything. Refresh it by
// running this in the Supabase SQL editor and pasting the result back:
//
//   select table_name || '|' || string_agg(
//            column_name || ':' ||
//            case data_type
//              when 'timestamp with time zone' then 'timestamptz'
//              when 'character varying'        then 'text'
//              else data_type end,
//            ', ' order by ordinal_position)
//     from information_schema.columns
//    where table_schema = 'public' and table_name like 'pi\\_%'
//    group by table_name order by table_name;
//
// then: node test/lib/build-schema.js
//
// TYPES USED TO BE INFERRED FROM THE COLUMN NAME, and that inference is what let
// a real bug through. Production had pi_meetings.attendee_ids as text while the
// name said jsonb, so the app's JSON array was rejected with a 400 in production
// and accepted here — the round trip passed in tests and lost every attendee
// list in the field. The dump settled several more: project_id and
// stakeholder_id are genuinely MIXED across tables (bigint on some, text on
// others), meeting_id and interaction_id are text, report_num and
// annual_report_year are text, and milestone_start / milestone_end are text
// rather than dates. A single guess per column name could not have been right.
const fs = require('fs');
const path = require('path');

// Only a fallback, for a column pasted in without a type. Anything that lands
// here is reported, because a guess is exactly what this file stopped doing.
const FALLBACK = 'text';
const TIMESTAMPS = new Set(['created_at','updated_at','published_at','editing_at','archived_at']);
// Which bigint ids are GENERATED ALWAYS AS IDENTITY rather than bigserial.
const IDENTITY_PK = new Set(['pi_projects','pi_stakeholders','pi_client_access',
                             'pi_parcels','pi_parcel_owners']);

const here = path.join(__dirname, '..');
const out = [];

// Supabase's two PostgREST roles. They do not exist in a bare cluster, so every
// `grant … to anon, authenticated` in sql/ used to fail here — and run.js
// swallows migration errors, which meant the harness could never see a grant at
// all. That is exactly how pi_parcels shipped granted to `anon` only: the
// database had the rows, the signed-in desktop app read them as `authenticated`
// and got nothing, and no test could tell.
out.push(`do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'anon') then
    create role anon nologin noinherit;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'authenticated') then
    create role authenticated nologin noinherit;
  end if;
end $$;`);
const guessed = [];
for (const line of fs.readFileSync(path.join(here, 'schema-columns.txt'), 'utf8').trim().split('\n')) {
  if (!line.trim()) continue;
  const [table, cols] = line.split('|');
  const defs = cols.split(',').map(c => c.trim()).filter(Boolean).map(spec => {
    const [col, declared] = spec.split(':').map(x => (x || '').trim());
    let ty = declared;
    if (!ty) { guessed.push(`${table}.${col}`); ty = FALLBACK; }
    if (col === 'id') {
      // The primary key's shape follows its declared type: text PKs are the
      // app-generated ids (comment periods, public comments, tribal), bigint
      // ones are generated by the database.
      if (ty === 'text') return 'id text primary key';
      return IDENTITY_PK.has(table)
        ? 'id bigint generated always as identity primary key'
        : 'id bigserial primary key';
    }
    if (col === 'token') return 'token uuid primary key';
    // OCC depends on updated_at defaulting to now(), so timestamps keep theirs.
    if (TIMESTAMPS.has(col) && ty === 'timestamptz') return `${col} timestamptz default now()`;
    return `${col} ${ty}`;
  });
  out.push(`create table ${table} (\n  ${defs.join(',\n  ')}\n);`);
}
if (guessed.length) {
  console.warn('  WARNING — no type declared, fell back to ' + FALLBACK + ':\n    '
    + guessed.join('\n    ') + '\n  Re-run the dump query in the header comment.');
}
out.push('create unique index pi_portal_links_proj_uniq on pi_portal_links(project_id);');
out.push('create unique index pi_parcels_proj_number_uniq on pi_parcels (project_id, lower(trim(parcel_number)));');
out.push('create unique index pi_parcel_owners_uniq on pi_parcel_owners (parcel_id, stakeholder_id);');
out.push('alter table pi_client_access add constraint pi_client_access_email_project_uniq unique (email, project_id);');

const dest = path.join(here, 'schema.sql');
fs.writeFileSync(dest, '-- GENERATED by test/lib/build-schema.js from test/schema-columns.txt.\n'
                     + '-- Do not edit by hand; edit schema-columns.txt and regenerate.\n\n'
                     + out.join('\n\n') + '\n');
console.log(`wrote ${dest} — ${out.length - 6} tables`);
