#!/usr/bin/env node
// Regenerates test/schema.sql from test/schema-columns.txt.
//
// schema-columns.txt is a verbatim dump of the live database's column lists —
// it is the reason the drift test means anything. Refresh it by running this in
// the Supabase SQL editor and pasting the result back as `table|col, col, …`:
//
//   select table_name, string_agg(column_name, ', ' order by ordinal_position)
//     from information_schema.columns
//    where table_schema = 'public' and table_name like 'pi\_%'
//    group by table_name order by table_name;
//
// then: node test/lib/build-schema.js
//
// Types are inferred by column name rather than dumped, which is a deliberate
// simplification — the tests care about which columns exist and about
// text-vs-bigint id handling, not about every check constraint.
const fs = require('fs');
const path = require('path');

const TYPES = {
  // project_id is TEXT, not bigint. fromSB() stringifies `id` but passes foreign
  // keys through raw, and the app compares them strictly — `p.id === x.projectId`
  // in _getIntStakeList(), `i.projectId === S.projectFilter` in renderInteractions.
  // Those work against the live database, which only holds if the column comes
  // back as a string. Typing it bigint here made the shim return numbers and
  // every project-scoped list came back empty for reasons that had nothing to do
  // with the code under test. (The live "text = bigint" seed error says the same.)
  id: 'bigint', project_id: 'text', stakeholder_id: 'bigint', group_id: 'bigint',
  issue_id: 'bigint', interaction_id: 'bigint', meeting_id: 'bigint', period_id: 'text',
  linked_stakeholder_id: 'bigint', org_id: 'bigint', user_id: 'uuid', token: 'uuid',
  sort_order: 'int', attendance_count: 'int', comment_cards: 'int', progress: 'int',
  contracted_qty: 'int', delivered_count: 'int', report_num: 'int', annual_report_year: 'int',
  is_master: 'boolean', is_archived: 'boolean', lep: 'boolean', underserved: 'boolean',
  is_lep: 'boolean', is_ej: 'boolean', follow_up: 'boolean', follow_up_done: 'boolean',
  equity_form_submitted: 'boolean', client_visible: 'boolean', include_internal: 'boolean',
  language_access_needed: 'boolean', moa_required: 'boolean', near_tribal_lands: 'boolean',
  cfr710_review: 'boolean', included_in_annual_report: 'boolean', bia_involvement: 'boolean',
  nepa_checklist: 'jsonb', phase_history: 'jsonb', nepa_stage_history: 'jsonb',
  sections: 'jsonb', snapshot: 'jsonb', attendee_ids: 'jsonb', dist_groups: 'jsonb',
};
const DATES = new Set(['start_date','end_date','precon_date','last_exported','due_date',
  'milestone_start','milestone_end','added_date','interaction_date','follow_up_due',
  'follow_up_resolved','meeting_date','date_raised','date_resolved','date_made',
  'fulfilled_date','comment_date','response_date','notification_date','response_deadline',
  'ura_notice_date','follow_up_date','period_start','period_end','hearing_date',
  'first_ad_date','second_ad_date','federal_register_date']);
// OCC columns default to now() in sql/2026-07-24_app_wide_occ.sql — the guard
// depends on that, so the test schema has to match.
const TIMESTAMPS = new Set(['created_at','updated_at','published_at','editing_at','archived_at']);
const TEXT_PK = new Set(['pi_comment_periods','pi_public_comments','pi_tribal_consultations']);
const IDENTITY_PK = new Set(['pi_projects','pi_stakeholders','pi_client_access']);

const here = path.join(__dirname, '..');
const out = [];
for (const line of fs.readFileSync(path.join(here, 'schema-columns.txt'), 'utf8').trim().split('\n')) {
  if (!line.trim()) continue;
  const [table, cols] = line.split('|');
  const defs = cols.split(',').map(c => c.trim()).map(c => {
    if (c === 'id') {
      if (TEXT_PK.has(table)) return 'id text primary key';
      if (IDENTITY_PK.has(table)) return 'id bigint generated always as identity primary key';
      return 'id bigserial primary key';
    }
    if (c === 'token') return 'token uuid primary key';
    if (TIMESTAMPS.has(c)) return `${c} timestamptz default now()`;
    if (DATES.has(c)) return `${c} date`;
    return `${c} ${TYPES[c] || 'text'}`;
  });
  out.push(`create table ${table} (\n  ${defs.join(',\n  ')}\n);`);
}
out.push('create unique index pi_portal_links_proj_uniq on pi_portal_links(project_id);');
out.push('alter table pi_client_access add constraint pi_client_access_email_project_uniq unique (email, project_id);');

const dest = path.join(here, 'schema.sql');
fs.writeFileSync(dest, '-- GENERATED by test/lib/build-schema.js from test/schema-columns.txt.\n'
                     + '-- Do not edit by hand; edit schema-columns.txt and regenerate.\n\n'
                     + out.join('\n\n') + '\n');
console.log(`wrote ${dest} — ${out.length - 2} tables`);
